### PR TITLE
Lint .tsx files by default

### LINKED ISSUE #21: Lint .tsx files by default
Just dropped this into a React Native project and noticed that it doesn't lint `.tsx` files by default. It does however lint `.jsx` files by default ☺️

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #21

### CODE REVIEW

**Comment by toddbluhm** [comment]
I like this! Nice find!

**Comment by toddbluhm** [comment]
Could you amend your commit message to something like `feat: lint .tsx files by default` or similar to comply with commit-lint requirements so the build passes. Thanks!

**Comment by LinusU** [comment]
Updated the commit message 👍 

Hmm, we might need some more work though, it doesn't seem to understand the tsx syntax 🤔 

I'm getting a lot of errors like "'React' is defined but never used", "'Text' is defined but never used" and "'View' is defined but never used"...

**Comment by LinusU** [comment]
Hmm, I think I'm running into this: https://github.com/typescript-eslint/typescript-eslint/issues/111

This should probably be fixed in `eslint-config-standard-with-typescript` though so we can go ahead with this PR! 🚀

**Comment by LinusU** [comment]
Actually, I think that the correct thing to do is to also extend `standard-react` in this package, as that is what's being done in the main standard package:

https://github.com/standard/standard/blob/fb7e2a3b4322decc9cbd9db7a55c8f4018861c92/eslintrc.json#L2

I've tried this locally and it fixes all my problems 😍 will add a commit for that now!

**Comment by LinusU** [comment]
Okay, rebased on master and everything should be fixed now 💪 

@toddbluhm it would be amazing if we could cut a new release as soon as this is merged, I'm starting a new project at work and really want to get Standard linting in from the start ☺️

**Comment by LinusU** [comment]
One final thing 😅, went thru the commit history and saw that you update the built files in the same commit that you edit the TypeScript files, so I rebased and did the same thing here. Should be golden now ✨

**Pull request merged**
